import type { Metadata } from "next";
import { ThemeProvider } from "@app-ds/ui/components/client";
import "@app-ds/ui/index.css";
import "./styles.css";

export const metadata: Metadata = {
  title: "Create Turborepo",
  description: "Generated by create turbo",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang="en">
      <ThemeProvider defaultTheme="dark">
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
